name: Build LLVM XCFrameworks

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-libffi:
    runs-on:
      macos-13
      
    strategy:
      fail-fast: false
      matrix:
        platformArch: [iphoneos, iphonesimulator, iphonesimulator-arm64, maccatalyst, maccatalyst-arm64]

    steps:
      - &checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install ninja

      - name: Build libffi
        run: |
          source build-llvm.sh
          build_libffi ${{ matrix.platformArch }}

      - name: Compress artifact
        run: tar -cJf libffi-${{ matrix.platformArch }}.tar.xz libffi-${{ matrix.platformArch }}

      - uses: actions/upload-artifact@v3
        with:
          name: libffi-${{ matrix.platformArch }}
          path: libffi-${{ matrix.platformArch }}.tar.xz

  build-llvm:
    needs: build-libffi
    runs-on:
      macos-13

    strategy:
      fail-fast: false
      matrix:
        platformArch: [iphoneos, iphonesimulator, iphonesimulator-arm64, maccatalyst, maccatalyst-arm64]

    timeout-minutes: 1200

    steps:
      - *checkout

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Extract artifacts
        run: |
          for f in $(find artifacts -name "*.tar.xz"); do
            tar -xJf "$f"
          done

      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: |
           ~/Library/Caches/Homebrew
           /usr/local/Homebrew
           /opt/homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/build-llvm.sh') }}

      - name: Install dependencies
        run: brew install ninja

      - name: Cache LLVM build
        uses: actions/cache@v3
        with:
          path: LLVM-${{ matrix.platformArch }}
          key: llvm-${{ matrix.platformArch }}-${{ hashFiles('build-llvm.sh') }}

      - name: Build LLVM
        run: |
          source build-llvm.sh
          build_llvm ${{ matrix.platformArch }}

      - name: Compress LLVM
        run: tar -cJf LLVM-${{ matrix.platformArch }}.tar.xz LLVM-${{ matrix.platformArch }}

      - uses: actions/upload-artifact@v3
        with:
          name: LLVM-${{ matrix.platformArch }}
          path: LLVM-${{ matrix.platformArch }}.tar.xz

  create-xcframework:
    needs: build-llvm
    runs-on:
      macos-13

    steps:
      - *checkout

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Extract artifacts
        run: |
          for f in $(find artifacts -name "*.tar.xz"); do
            tar -xJf "$f"
          done

      - name: Create Intel XCFramework
        run: |
          source build-llvm.sh
          create_xcframework iphoneos iphonesimulator maccatalyst

      - name: Package Intel XCFramework
        run: tar -cJf LLVM_Intel.xcframework.tar.xz LLVM.xcframework

      - uses: actions/upload-artifact@v3
        with:
          name: LLVM_Intel
          path: LLVM_Intel.xcframework.tar.xz

      - uses: actions/upload-artifact@v3
        with:
          name: libclang
          path: libclang.tar.xz

      - name: Create Apple Silicon XCFramework
        run: |
          source build-llvm.sh
          rm -rf LLVM.xcframework
          create_xcframework iphoneos iphonesimulator-arm64 maccatalyst-arm64

      - name: Package Apple Silicon XCFramework
        run: tar -cJf LLVM_M1.xcframework.tar.xz LLVM.xcframework

      - uses: actions/upload-artifact@v3
        with:
          name: LLVM_M1
          path: LLVM_M1.xcframework.tar.xz
